baseURL = "https://blog.vincexu.link"
defaultContentLanguage = "zh-cn"
enableEmoji = true
hasCJKLanguage = true
languageCode = "zh-CN"
theme = "DoIt"
title = "Hopter 的博客"

[author]
email = "xf.vince@gmail.com"
gravatarEmail = "xf.vince@gmail.com"
link = "https://github.com/hoptercat"
name = "Vince Xu"

[params]
gitRepo = "https://github.com/hoptercat/hoptercat.github.io"
version = "0.2.X"

[params.rss]
rss = 10

[params.home.profile]
enable = true
gravatarEmail = "xf.vince@gmail.com"
social = true
title = "Hopter 的博客"
typeit = false

[params.footer]
author = true

[taxonomies]
author = "authors"
category = "categories"
series = "series"
tag = "tags"

[params.social]
Email = "xf.vince@gmail.com"
GitHub = "hoptercat"

[params.page.outdatedArticleReminder]
enable = false

[params.page.comment]
enable = true
[params.page.comment.utterances]
darkTheme = "github-dark"
enable = true
issueTerm = "pathname"
label = "comment"
lightTheme = "github-light"
repo = "hoptercat/hoptercat.github.io"

[[menu.main]]
identifier = "posts"
name = "文章"
url = "/posts/"
weight = 1
[[menu.main]]
identifier = "tags"
name = "标签"
url = "/tags/"
weight = 2
[[menu.main]]
identifier = "rss"
name = "订阅"
url = "/index.xml"
weight = 4
[[menu.main]]
identifier = "authors"
name = "作者"
url = "/authors/"
weight = 5
[[menu.main]]
identifier = "github"
name = "源码"
post = ""
title = "GitHub"
url = "https://github.com/hoptercat/hoptercat.github.io"
weight = 9
[markup]
[markup.highlight]
noClasses = false
